spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
#  全局接收日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8